import type { TenantBookingAcceptanceType } from '../../booking/entities/booking-acceptance-type.type';
import type { PlanTier } from './plan-tier.type';
import type { SubscriptionStatus } from './subscription-status.type';
import type { CalendarCardPreferences } from './calendar-card-preferences.type';
import type { PayoutFrequency } from './payout-frequency.type';

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  banner_url: string | null;
  banner_overlay_color: string;
  banner_overlay_opacity: number;
  address_cep: string | null;
  address_street: string | null;
  address_number: string | null;
  address_complement: string | null;
  address_neighborhood: string | null;
  address_city: string | null;
  address_state: string | null;
  primary_color: string;
  admin_secondary_color_light: string;
  admin_secondary_color_dark: string;
  contact_phone: string | null;
  deposit_feature_enabled: boolean;
  deposit_application_fee_percent: number | null;
  require_customer_email_confirmation: boolean;
  allow_customer_self_cancellation: boolean;
  booking_acceptance_type: TenantBookingAcceptanceType;
  booking_slot_interval_minutes: number;
  owner_id: string | null;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  stripe_connect_account_id: string | null;
  stripe_connect_charges_enabled: boolean;
  stripe_connect_details_submitted: boolean;
  subscription_status: SubscriptionStatus;
  subscription_expires_at: string | null;
  trial_starts_at: string | null;
  trial_ends_at: string | null;
  pre_subscription_trial_ends_at: string | null;
  plan_tier: PlanTier;
  calendar_card_preferences: CalendarCardPreferences;
  enable_payout_control: boolean;
  payout_frequency: PayoutFrequency;
  enable_referral_program: boolean;
  referrer_points_bonus: number;
  referee_points_bonus: number;
  initial_setup_completed_at: string | null;
  initial_setup_version: number | null;
  initial_setup_settings_visited_at: string | null;
  created_at: string;
  updated_at: string;
}
