export const AFFILIATE_TERMS_VERSION = '2026-09-01';
export const AFFILIATE_DEFAULT_COMMISSION_PERCENT = 20;
export const AFFILIATE_PAYOUT_MINIMUM_CENTS = 5000;
export const AFFILIATE_COOKIE_MAX_AGE_DAYS = 90;
